# Generated by Django 4.0.3 on 2022-04-04 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('nib', models.IntegerField(blank=True, db_column='NIB', null=True)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
                ('data_de_nascimento', models.DateTimeField(blank=True, db_column='Data de nascimento', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telemovel', models.CharField(blank=True, db_column='Telemovel', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_de_inicio', models.DateTimeField(blank=True, db_column='Data de inicio', null=True)),
                ('data_de_termino', models.DateTimeField(blank=True, db_column='Data de termino', null=True)),
                ('clienteid', models.ForeignKey(db_column='ClienteID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dia', models.IntegerField(db_column='Dia')),
                ('mes', models.IntegerField(db_column='Mes')),
                ('ano', models.IntegerField(db_column='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('morada', models.CharField(blank=True, db_column='Morada', max_length=255, null=True)),
                ('capacidade', models.IntegerField(db_column='Capacidade')),
                ('zonas', models.IntegerField(db_column='Zonas')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('periodicidade', models.CharField(blank=True, db_column='Periodicidade', max_length=255, null=True)),
                ('hora_de_inicio', models.TimeField(blank=True, db_column='Hora de inicio', null=True)),
                ('hora_de_termino', models.TimeField(blank=True, db_column='Hora de termino', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistoMovimento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_de_entrada', models.DateTimeField(db_column='Data de entrada', default=datetime.datetime.now)),
                ('data_de_saida', models.DateTimeField(blank=True, db_column='Data de saida', null=True)),
                ('provas', models.CharField(blank=True, db_column='Provas', max_length=255, null=True)),
                ('parqueid', models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_da_zona', models.IntegerField(db_column='Numero da zona')),
                ('lugares', models.IntegerField(db_column='Lugares')),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, db_column='Modelo', max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, db_column='Matricula', max_length=255, null=True)),
                ('contratoid', models.ForeignKey(db_column='ContratoID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.contrato')),
                ('registo_movimentoid', models.ForeignKey(db_column='Registo-movimentoID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.registomovimento')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPrecos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('preco_por_hora', models.FloatField(db_column='Preco por hora')),
                ('taxa_por_hora', models.FloatField(db_column='Taxa por hora')),
                ('taxa_noturna', models.FloatField(db_column='Taxa noturna')),
                ('taxa_da_multa', models.FloatField(db_column='Taxa da multa')),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data_de_inicio', models.DateTimeField(blank=True, db_column='Data de inicio', null=True)),
                ('data_de_termino', models.DateTimeField(blank=True, db_column='Data de termino', null=True)),
                ('parqueid', models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
                ('viaturaid', models.ForeignKey(db_column='ViaturaID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.viatura')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('montante', models.FloatField(db_column='Montante')),
                ('estado_do_pagamento', models.TextField(db_column='Estado do pagamento')),
                ('data_de_vencimento', models.DateTimeField(blank=True, db_column='Data de vencimento', null=True)),
                ('contratoid', models.ForeignKey(db_column='ContratoID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_do_lugar', models.IntegerField(db_column='Numero do lugar')),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('contratoid', models.ForeignKey(db_column='ContratoID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.contrato')),
                ('reservaid', models.ForeignKey(db_column='ReservaID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.reserva')),
                ('viaturaid', models.ForeignKey(db_column='ViaturaID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.viatura')),
                ('zonaid', models.ForeignKey(db_column='ZonaID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('funcao', models.CharField(blank=True, db_column='Funcao', max_length=255, null=True)),
                ('permissao', models.IntegerField(db_column='Permissao')),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('permissao', models.IntegerField(db_column='Permissao')),
                ('parqueid', models.ForeignKey(db_column='ParqueID', on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.parque')),
            ],
        ),
    ]
