# Generated by Django 4.0.3 on 2022-04-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='periodicidadeid',
            field=models.ForeignKey(db_column='PeriodicidadeID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.periodicidade'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clienteid',
            field=models.ForeignKey(db_column='ClienteID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.cliente'),
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
    ]
