# Generated by Django 4.0.3 on 2022-04-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManagement', '0002_contrato_periodicidadeid_alter_contrato_clienteid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='periodicidade',
            name='hora_de_inicio',
        ),
        migrations.RemoveField(
            model_name='periodicidade',
            name='hora_de_termino',
        ),
        migrations.AddField(
            model_name='dia',
            name='nome',
            field=models.CharField(blank=True, db_column='Periodicidade', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='periodicidade',
            name='dia_semana_id',
            field=models.ForeignKey(db_column='DiaID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.dia'),
        ),
        migrations.AddField(
            model_name='periodicidade',
            name='horario',
            field=models.CharField(blank=True, db_column='Horario', max_length=255, null=True),
        ),
    ]
