# Generated by Django 4.0.3 on 2022-05-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManagement', '0003_remove_dia_ano_remove_dia_dia_remove_dia_mes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicidade',
            name='dia_semana_id',
        ),
        migrations.AddField(
            model_name='dia',
            name='periodicidadeid',
            field=models.ForeignKey(db_column='PeriodicidadeID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.periodicidade'),
        ),
        migrations.AlterField(
            model_name='dia',
            name='nome',
            field=models.CharField(blank=True, db_column='Dia', max_length=255, null=True),
        ),
    ]
