# Generated by Django 4.0.3 on 2022-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_de_inicio',
            field=models.TimeField(blank=True, db_column='Hora de inicio', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_de_termino',
            field=models.TimeField(blank=True, db_column='Hora de termino', null=True),
        ),
    ]
